### ISSUE TITLE
Digit validation

### ISSUE THREAD

**Issue by vasundhara785** [dongri/phonenumber#12]
1.It is giving the country code even if the number contains alphanumeric characters
2.Some countries validations are missed due to length/prefix mismatch.

Thanks.

**Comment by dongri** [comment]
@vasundhara785 Can you give me a sample number?

**Comment by vasundhara785** [comment]
@dongri 62895349866066 (Indonesia number)

**Comment by dongri** [comment]
@vasundhara785 Indonesia phone number length fixed.

**Comment by vasundhara785** [comment]
@dongri 

Can i know on what basis the length validation / prefix is being done?

**Comment by dongri** [comment]
https://en.wikipedia.org/wiki/E.164
https://en.wikipedia.org/wiki/List_of_country_calling_codes

**Comment by vasundhara785** [comment]
@dongri 
How to differentiate between  singapore numbers (65XXXXXXXX) and india numbers with(65XXXXXXXX)?

**Comment by dongri** [comment]
https://github.com/dongri/phonenumber/blob/master/iso3166.go#L791-L795
India is "91"
https://en.wikipedia.org/wiki/Telephone_numbers_in_India

**Comment by vasundhara785** [comment]
No if the user doesn't specify "91" for india numbers

**Comment by dongri** [comment]
That's impossible...
Please add the country code.
