### ISSUE TITLE
Short number

### ISSUE THREAD

**Issue by mwolff44** [dongri/phonenumber#15]
Hi,
Did you plan to add short numbers and urgency numbers matching ?
Regards

**Comment by dongri** [comment]
Hi, @mwolff44 
What does it mean? Give me a sample.
Thank you

**Comment by mwolff44** [comment]
Hi,
In France there are many short numbers : 
* urgency : 15, 16, 17, 112, 116xxx ...
* value added services 36xx
* information : 118xxx
* ...
Regards

**Comment by dongri** [comment]
Hi, @mwolff44 
I see what you mean.
However, this repository is E.164 compliant, so there are no plans to support emergency numbers. Sorry.

**Comment by mwolff44** [comment]
ok, thx for your answer
