### ISSUE TITLE
Bahrain Mobile Phone Numbers

### ISSUE THREAD

**Issue by emrullahshn** [dongri/phonenumber#19]
Currently library supports just "3" prefix for begening in Bahrain numbers. But there are "6" and "7" prefix. So could you add new prefixes? For example +97366622125

```
	i.Alpha2 = "BH"
	i.Alpha3 = "BHR"
	i.CountryCode = "973"
	i.CountryName = "Bahrain"
	i.MobileBeginWith = []string{"3"}
	i.PhoneNumberLengths = []int{8}
	iso3166Datas = append(iso3166Datas, i)
```

**Comment by 4rakcheev** [comment]
The issue already fixed by @emrullahshn  https://github.com/dongri/phonenumber/commit/1e58a2b4cf97e2e5bae8175a921402010780b6c4.

@dongri @emrullahshn Please close the issue.

**Comment by dongri** [comment]
@emrullahshn Thanks for confirm
