### ISSUE TITLE
Calling GetISO3166ByNumber() with withLandline=true break it for Canadian phone numbers

### ISSUE THREAD

**Issue by haizaar** [dongri/phonenumber#23]
US and CA have the same country code, hence if you call `GetISO3166ByNumber()` with `withLandline=true` it will always return `US` even for Canadian *mobile* numbers - as per https://github.com/dongri/phonenumber/blob/master/phonenumber.go#L106

To fix this, I suggest the library code to be reworked to match the longest matching prefix of country_code+mobile_prefix.

**Comment by 4rakcheev** [comment]
Fixed by PR https://github.com/dongri/phonenumber/pull/29

**Comment by 4rakcheev** [comment]
@haizaar @dongri could you please close the issue?
