### ISSUE TITLE
UK Telephone Numbers

### ISSUE THREAD

**Issue by ainsleyclark** [dongri/phonenumber#45]
It's common for the `UK` mobiles to start with `07`. For example: `07933846223`

But it seems that `Gabon` already has this.

```go
i.Alpha2 = "GA"
i.Alpha3 = "GAB"
i.CountryCode = "241"
i.CountryName = "Gabon"
i.MobileBeginWith = []string{"05", "06", "07"}
i.PhoneNumberLengths = []int{8}
iso3166Datas = append(iso3166Datas, i)

i.Alpha2 = "GB"
i.Alpha3 = "GBR"
i.CountryCode = "44"
i.CountryName = "United Kingdom"
i.MobileBeginWith = []string{"7"}
i.PhoneNumberLengths = []int{10}
iso3166Datas = append(iso3166Datas, i)
```

This results in default country code `17933846223`

**Comment by dongri** [comment]
@ainsleyclark Which function did you call, and what were the results?

**Comment by ainsleyclark** [comment]
Hi @dongri 


```go
func FormatTelephone(number string) (string, error) {
	if number == "" {
		return "", errors.New("telephone cannot be empty")
	}
	c := phonenumber.GetISO3166ByNumber(number, true)
	tel := phonenumber.ParseWithLandLine(number, c.Alpha3)
	return formatInternal(number, tel)
}
```

**Comment by dongri** [comment]
@ainsleyclark This library provides several features, but it seems that `GetISO3166ByNumber` does not work well with landline numbers.  
You might want to write it like this:

```go
tel := phonenumber.ParseWithLandLine("07933846223", "GB")
```

**Comment by ainsleyclark** [comment]
Thanks @dongri

I don't have access the callers country though, just the number. Is there another workaround?

Thanks again.

**Comment by dongri** [comment]
I added a function to retrieve the country from a mobile number.
https://github.com/dongri/phonenumber/blob/main/examples/main.go#L10
Can use v0.1.7

**Comment by ainsleyclark** [comment]
Thanks for your reply.

If I don't know if it's a mobile or landline what would you suggest?

**Comment by dongri** [comment]
If there is no country code attached, I think it would be difficult to determine the number with just a landline.

**Comment by ainsleyclark** [comment]
Thanks for your reply, is there a way to determine if a given input is a mobile number?

**Comment by dongri** [comment]
As far as I know, if there is no country code, I think it is impossible to determine.
