### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by or-else** [dongri/phonenumber#8]
Hi 

I'm think about using this code in my project and wonder if it's maintained. It seems like a few people have been forking and actively updating the forks but nothing went back to the upstream:

https://github.com/4rakcheev/phonenumber/commits/master -- this seems to be actively maintained.
https://github.com/OpenStars/phonenumber/commits/master
https://github.com/cooltech-bs/phonenumber/commits/master

What are your plans for maintaining/updating the phone # data?

Thanks!

**Comment by dongri** [comment]
@or-else Hi 
I'm going to do maintenance. However, the phone number of each country was also changed and I thought there was nothing I could do without a pull request.

**Comment by or-else** [comment]
Regarding pull requests: the license permits you or anyone to create PRs from forks. You can just merge https://github.com/4rakcheev/phonenumber/commits/master back to upstream.

**Comment by dongri** [comment]
Ok, If it's not a big problem looking at that repo I will take it into this repo. I'll call you when I'm done.

**Comment by dongri** [comment]
@or-else Hi
https://github.com/dongri/phonenumber/pull/9

Merged from https://github.com/4rakcheev/phonenumber/commits/master

**Comment by or-else** [comment]
Thanks!
